language: go

os:
  - linux
  - osx

go:
  - 1.5
  - 1.9
  - tip

env:
  - GO15VENDOREXPERIMENT=1

install:
  - git submodule update --init --recursive

script:
  - go test -v $(go list ./...|grep -v /vendor/)

matrix:
  allow_failures:
    - go: tip
